# Auto-generated by the ReproIt/reproit release workflow. Do not edit by hand.
class Reproit < Formula
  desc "Deterministic UI fuzzer: find a bug once, reproduce it forever"
  homepage "https://reproit.com"
  version "0.1.126"
  license "Elastic-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ReproIt/reproit/releases/download/v0.1.126/reproit-v0.1.126-aarch64-apple-darwin.tar.gz"
      sha256 "f3deb70e2b718da4be89bb0682fe4e199d1e2c9c91383223d1ab1e509d100614"
    end
    on_intel do
      url "https://github.com/ReproIt/reproit/releases/download/v0.1.126/reproit-v0.1.126-x86_64-apple-darwin.tar.gz"
      sha256 "563533bd7fe9eae943fec645a2b0d7f2b93450a5a2812bd0630e32412d90de1c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ReproIt/reproit/releases/download/v0.1.126/reproit-v0.1.126-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7123ffa3d46c2d0b8f5d2f4c8ff6bf065a9ad30f0f11977bdebe3b1e59858c66"
    end
  end

  def install
    bin.install "reproit"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/reproit --version")
  end
end
