# Auto-generated by the ReproIt/reproit release workflow. Do not edit by hand.
class Reproit < Formula
  desc "Deterministic UI fuzzer: find a bug once, reproduce it forever"
  homepage "https://reproit.com"
  version "0.1.93"
  license "Elastic-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ReproIt/reproit/releases/download/v0.1.93/reproit-v0.1.93-aarch64-apple-darwin.tar.gz"
      sha256 "9b0087f3c68eb3f202244109ecf7cde40aa917918ee7736b5a1cde08a01a24c1"
    end
    on_intel do
      url "https://github.com/ReproIt/reproit/releases/download/v0.1.93/reproit-v0.1.93-x86_64-apple-darwin.tar.gz"
      sha256 "93247345809d10d7ce7f2b23f23ffdbac9bb63f9881c5c3045d8b910c2ee4f4e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ReproIt/reproit/releases/download/v0.1.93/reproit-v0.1.93-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e40776dab10c6074a0886cf68fde861fb5e9612f4925527a2f9f25130e92f838"
    end
  end

  def install
    bin.install "reproit"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/reproit --version")
  end
end
