# Auto-generated by the ReproIt/reproit release workflow. Do not edit by hand.
class Reproit < Formula
  desc "Deterministic UI fuzzer: find a bug once, reproduce it forever"
  homepage "https://reproit.com"
  version "0.1.50"
  license "Elastic-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ReproIt/reproit/releases/download/v0.1.50/reproit-v0.1.50-aarch64-apple-darwin.tar.gz"
      sha256 "b55d441dc6cad4ce606926049062644b973eda9216da0e8bd0c7feabcd57cd3b"
    end
    on_intel do
      url "https://github.com/ReproIt/reproit/releases/download/v0.1.50/reproit-v0.1.50-x86_64-apple-darwin.tar.gz"
      sha256 "3fef4dd526b17e0cd3ad6f2b1613a1d6cb05f13747dd42a02760f856b030f5c5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ReproIt/reproit/releases/download/v0.1.50/reproit-v0.1.50-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6e4277f9f403b63e0b1422dd02444dcfaaeee19258aba39243f093648186a0b4"
    end
  end

  def install
    bin.install "reproit"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/reproit --version")
  end
end
